Repository BCSDLab/BCSD_INTERNAL_WEB, pull requests merged in 2024-02, with the labels that each got.

#3 [공통] @emotion/react css prop 설정 적용 및 기본 레이아웃
  .pnp.cjs
  .yarn/install-state.gz
  package.json
  src/assets/image/BCSD_logo-01.png
  src/index.css
  src/layout/DefaultLayout/index.tsx
  src/layout/DefaultLayout/style.ts
  src/page/MemberInfo/index.tsx
  src/page/MemberInfo/style.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#7 [공통] 이미지경로 수정, favicon, title 추가
  index.html
  src/assets/image/BCSD_logo-01.png
  src/const/colors/style.ts
  src/layout/DefaultLayout/index.tsx
  src/layout/DefaultLayout/style.ts
Labels: bug

#20 [회원관리] 회원정보 수정 구현
  .eslintrc.cjs
  .yarn/install-state.gz
  src/api/members/index.ts
  src/component/modal/memberInfoModal/index.tsx
  src/component/modal/memberInfoModal/style.ts
  src/model/member.ts
  src/page/MemberInfo/ListLayout/index.tsx
  src/query/members.ts
Labels: enhancement

#24 [회원관리] 회원정보 생성
  src/api/members/index.ts
  src/component/modal/memberCreateModal/index.tsx
  src/component/modal/memberCreateModal/style.ts
  src/model/member.ts
  src/page/MemberInfo/index.tsx
  src/query/members.ts
Labels: enhancement

#26 [회원관리] 회원정보 수정 모달 수정가능정보 추가구현
  src/component/modal/memberInfoModal/index.tsx
Labels: enhancement

#30 [공통] 회원정보 페이지 공통 사이드바 적용
  .yarn/install-state.gz
  src/App.tsx
  src/component/modal/memberInfoModal/index.tsx
  src/component/modal/memberInfoModal/style.ts
  src/page/MemberInfo/index.tsx
  src/page/MemberInfo/style.ts
Labels: Refactoring, UI

#37 [회원관리] 마이페이지
  .yarn/install-state.gz
  index.html
  src/App.tsx
  src/api/members/index.ts
  src/component/modal/memberCreateModal/index.tsx
  src/component/modal/memberInfoModal/index.tsx
  src/const/colors/style.ts
  src/layout/SideBar/index.tsx
  src/model/member.ts
  src/page/MemberInfo/index.tsx
  src/page/MemberInfo/style.ts
  src/page/MyPage/index.tsx
  src/page/MyPage/style.ts
  src/query/members.ts
  tsconfig.json
Labels: enhancement, UI

#42 [회원관리] 탈퇴회원만 조회되도록 수정
  src/api/members/index.ts
  src/page/MemberInfo/ListLayout/index.tsx
  src/query/members.ts
Labels: Refactoring

#47 [회원관리] 탈퇴회원 정보수정 시 렌더링이 되지 않던 버그 수정
  src/query/members.ts
Labels: bug

#44 [회비 생성] 회비 생성 페이지 에러 수정
  src/model/dues/allDues.ts
  src/page/DuesSetup/index.tsx
Labels: bug

#75 [회원생성] 비밀번호 SHA256암호화, 버튼 충돌 수정, 생성 후 폼 초기화
  src/component/modal/memberCreateModal/index.tsx
  src/page/MemberInfo/ListLayout/index.tsx
  src/page/MemberInfo/TrackFilter/index.tsx
  src/page/MemberInfo/index.tsx
  src/page/MemberInfo/style.ts
Labels: bug, Refactoring

#77 [회원정보] 회원 권한에 따라 수정, 생성 접근 제한
  src/page/MemberInfo/ListLayout/index.tsx
  src/page/MemberInfo/index.tsx
Labels: enhancement
