Repository BCSDLab/BCSD_INTERNAL_WEB, pull requests merged in 2024-05, with the labels that each got.

#168 [슬랙봇] 슬랙 동기화 버튼 추가
  src/api/admin/index.ts
  src/layout/TopBar/index.tsx
  src/layout/TopBar/style.ts
  src/model/admin.ts
  src/query/admin.ts
Labels: enhancement

#169 [공통] useMediaQuery 추가 및 공통 페이지 모바일 뷰 추가
  src/layout/SideBar/style.ts
  src/layout/TopBar/style.ts
  src/util/hooks/useMediaQuery.ts
Labels: enhancement

#171 [공통] 토큰만료시 로그아웃 로직 추가
  .yarn/install-state.gz
  src/store/loginStore.ts
Labels: bug

#176 [구글 캘린더] 구글 캘린더 연동
  .pnp.cjs
  .yarn/cache/@esbuild-darwin-arm64-npm-0.19.12-09699ac6cb-8.zip
  .yarn/cache/@esbuild-win32-x64-npm-0.19.12-1bf4cb5f20-8.zip
  .yarn/cache/@maxim_mazurok-gapi.client.calendar-v3-npm-0.0.20240425-12052d25f1-c46ae4433c.zip
  .yarn/cache/@maxim_mazurok-gapi.client.discovery-v1-npm-0.1.20200806-e22696dee7-18b9360788.zip
  .yarn/cache/@rollup-rollup-darwin-arm64-npm-4.9.6-e7e3fa5308-8.zip
  .yarn/cache/@rollup-rollup-win32-x64-msvc-npm-4.9.6-416b5a71e5-8.zip
  .yarn/cache/@types-gapi-npm-0.0.47-e25311ceb0-9f18e5d22a.zip
  .yarn/cache/@types-gapi.auth2-npm-0.0.60-0818407a4c-a42a417831.zip
  .yarn/cache/@types-gapi.client-npm-1.0.8-40175e07e7-add67fad25.zip
  .yarn/cache/@types-gapi.client.calendar-npm-3.0.12-dbc4f7961f-4365b386ea.zip
  .yarn/cache/@types-gapi.client.calendar-v3-npm-0.0.4-1ef36fd353-ee2c4bdc74.zip
  .yarn/cache/@types-gapi.client.discovery-v1-npm-0.0.4-da690f7335-51d20e6cfb.zip
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/gapi-script-npm-1.2.0-974f1c2f4e-f61140855e.zip
  .yarn/install-state.gz
  .yarnrc.yml
  package.json
  src/config/constants.ts
  src/page/Reservation/view/Month.tsx
  src/page/Reservation/view/Month/DetailInfomation.tsx
  src/ts/googleapi.ts
  yarn.lock
Labels: enhancement

#172 [회비] 회비 확인 모바일
  src/component/YearPagination/index.tsx
  src/component/YearPagination/style.ts
  src/layout/TopBar/index.tsx
  src/page/DuesManagement/index.tsx
  src/page/EditDues/index.tsx
  src/page/PersonalDues/index.tsx
  src/page/PersonalDues/style.ts
  src/util/hooks/useQueryParam.ts
Labels: enhancement

#178 [팀 관리페이지] 팀 관리페이지 구현
  src/api/members/index.ts
  src/api/teams/index.ts
  src/component/alertModal/index.tsx
  src/component/alertModal/style.ts
  src/component/modal/teamAddMemberModal/index.tsx
  src/component/modal/teamAddMemberModal/style.ts
  src/component/modal/teamCreateModal/index.tsx
  src/component/modal/teamUpdateModal/index.tsx
  src/component/modal/teamUpdateModal/style.ts
  src/layout/SideBar/index.tsx
  src/page/Team/index.tsx
  src/page/Team/style.ts
  src/query/members.ts
Labels: enhancement, UI
