Repository BCSDLab/BCSD_INTERNAL_WEB, pull requests merged in 2024-03, with the labels that each got.

#76 [마이페이지] 프로필 이미지 미업로드시 기본 프로필 적용
  src/page/MyPage/index.tsx
  src/page/MyPage/style.ts
Labels: Refactoring

#78 회비 생성 페이지 이슈 수정
  src/page/DuesSetup/index.tsx
  src/page/DuesSetup/style.ts
Labels: bug

#80 [회원정보] 그리드 레이아웃 구현
  src/component/modal/memberInfoModal/index.tsx
  src/index.css
  src/layout/SideBar/index.tsx
  src/model/member.ts
  src/page/MemberInfo/GridLayout/index.tsx
  src/page/MemberInfo/GridLayout/style.ts
  src/page/MemberInfo/ListLayout/index.tsx
  src/page/MemberInfo/index.tsx
  src/page/MemberInfo/style.ts
Labels: enhancement

#79 회비 납부 페이지, 회비 수정 페이지 이슈 해결
  src/page/DuesManagement/index.tsx
  src/page/DuesManagement/style.ts
  src/page/DuesSetup/index.tsx
  src/page/DuesSetup/style.ts
  src/page/EditDues/index.tsx
  src/page/EditDues/style.ts
  src/util/constants/status.ts
Labels: bug

#85 [회비 변경] 회비 취소 기능 추가
  .yarn/install-state.gz
  src/api/dues/index.ts
  src/page/DuesSetup/index.tsx
  src/page/EditDues/index.tsx
  src/query/dues.ts
Labels: enhancement

#88 회원 정보 수정 중 권한을 추가하여 수정이 안되는 에러 해결
  src/model/member.ts
Labels: bug

#89 [트랙관리] 트랙관리 페이지 구현
  .yarn/install-state.gz
  src/App.tsx
  src/api/members/index.ts
  src/api/tracks/index.ts
  src/component/modal/trackCreateModal/index.tsx
  src/component/modal/trackCreateModal/style.ts
  src/component/modal/trackUpdateModal/index.tsx
  src/component/modal/trackUpdateModal/style.ts
  src/const/urls/index.ts
  src/layout/SideBar/index.tsx
  src/layout/TopBar/index.tsx
  src/layout/TopBar/style.ts
  src/model/member.ts
  src/model/track.ts
  src/page/Admin/index.tsx
  src/page/MemberInfo/GridLayout/index.tsx
  src/page/MyPage/index.tsx
  src/page/MyPage/style.ts
  src/page/SignUp/index.tsx
  src/page/SnackBar/index.tsx
  src/page/Track/index.tsx
  src/page/Track/style.ts
  src/query/tracks.ts
Labels: enhancement

#90 [회원정보] 회원정보 수정 시 권한도 수정할 수 있도록 구현
  src/component/modal/memberInfoModal/index.tsx
  src/model/member.ts
  src/page/MemberInfo/ListLayout/index.tsx
  src/page/MyPage/index.tsx
Labels: enhancement

#94 [공통] 타이틀로고 클릭시 라우팅 추가
  src/layout/SideBar/index.tsx
  src/layout/SideBar/style.ts
  src/layout/TopBar/index.tsx
Labels: enhancement

#93 [직책 관리] 직책 관리 페이지 추가
  src/App.tsx
  src/api/jobs/index.ts
  src/component/modal/createJobModal/index.tsx
  src/component/modal/createJobModal/style.ts
  src/component/modal/memberInfoModal/index.tsx
  src/component/modal/memberInfoModal/style.ts
  src/component/modal/updateJobModal/index.tsx
  src/component/modal/updateJobModal/style.ts
  src/layout/SideBar/index.tsx
  src/layout/TopBar/index.tsx
  src/model/job.ts
  src/page/MemberInfo/GridLayout/index.tsx
  src/page/Role/hook/useFindJob.ts
  src/page/Role/index.tsx
  src/page/Role/style.ts
  src/query/jobs.ts
Labels: enhancement

#106 직책 수정 모달에 선택한 연도의 데이터가 전달되도록 수정
  src/component/modal/updateJobModal/index.tsx
  src/page/Role/index.tsx
Labels: bug

#113 2차 스프린트 UI 이슈 해결
  src/page/Admin/index.tsx
  src/page/MemberInfo/GridLayout/index.tsx
  src/page/MemberInfo/GridLayout/style.ts
  src/page/MemberInfo/ListLayout/index.tsx
  src/page/MemberInfo/index.tsx
  src/page/MemberInfo/style.ts
  src/page/SignUp/index.tsx
Labels: bug, UI

#116 로그인 성공 시 진입 에러 해결
  src/App.tsx
  src/layout/DefaultLayout/index.tsx
  src/layout/SideBar/index.tsx
  src/layout/TopBar/index.tsx
  src/page/SignIn/index.tsx
  src/query/members.ts
  src/util/constants/path.ts
Labels: bug

#118 [동방 예약] 동방 예약 페이지 구현
  .yarn/install-state.gz
  src/App.tsx
  src/api/reservations/index.ts
  src/layout/SideBar/index.tsx
  src/layout/TopBar/index.tsx
  src/model/reservations.ts
  src/page/Reservation/index.tsx
  src/page/Reservation/style.ts
  src/page/Reservation/view/Week/index.tsx
  src/page/Reservation/view/Week/modal/createReservationModal/index.tsx
  src/page/Reservation/view/Week/modal/createReservationModal/style.ts
  src/page/Reservation/view/Week/modal/displayTime/index.tsx
  src/page/Reservation/view/Week/modal/displayTime/style.ts
  src/page/Reservation/view/Week/modal/modifyReservationModal/index.tsx
  src/page/Reservation/view/Week/modal/modifyReservationModal/style.ts
  src/page/Reservation/view/Week/styles.ts
  src/query/reservations.ts
  src/util/constants/path.ts
  src/util/constants/time.ts
Labels: enhancement

#119 [회비] 회비 페이지 멘토 인원 삭제
  src/page/DuesManagement/index.tsx
  src/page/EditDues/index.tsx
Labels: bug
